/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfilesRouteImport } from './routes/profiles'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LaboratoryRouteImport } from './routes/laboratory'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfilesIndexRouteImport } from './routes/profiles.index'
import { Route as ProfilesManageRouteImport } from './routes/profiles.manage'
import { Route as ProfilesProfileIdQuestRouteImport } from './routes/profiles.$profileId.quest'
import { Route as ProfilesProfileIdPortfolioRouteImport } from './routes/profiles.$profileId.portfolio'
import { Route as ProfilesProfileIdMentorsRouteImport } from './routes/profiles.$profileId.mentors'
import { Route as ProfilesProfileIdChallengesRouteImport } from './routes/profiles.$profileId.challenges'

const ProfilesRoute = ProfilesRouteImport.update({
  id: '/profiles',
  path: '/profiles',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LaboratoryRoute = LaboratoryRouteImport.update({
  id: '/laboratory',
  path: '/laboratory',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilesIndexRoute = ProfilesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfilesRoute,
} as any)
const ProfilesManageRoute = ProfilesManageRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => ProfilesRoute,
} as any)
const ProfilesProfileIdQuestRoute = ProfilesProfileIdQuestRouteImport.update({
  id: '/$profileId/quest',
  path: '/$profileId/quest',
  getParentRoute: () => ProfilesRoute,
} as any)
const ProfilesProfileIdPortfolioRoute =
  ProfilesProfileIdPortfolioRouteImport.update({
    id: '/$profileId/portfolio',
    path: '/$profileId/portfolio',
    getParentRoute: () => ProfilesRoute,
  } as any)
const ProfilesProfileIdMentorsRoute =
  ProfilesProfileIdMentorsRouteImport.update({
    id: '/$profileId/mentors',
    path: '/$profileId/mentors',
    getParentRoute: () => ProfilesRoute,
  } as any)
const ProfilesProfileIdChallengesRoute =
  ProfilesProfileIdChallengesRouteImport.update({
    id: '/$profileId/challenges',
    path: '/$profileId/challenges',
    getParentRoute: () => ProfilesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/feed': typeof FeedRoute
  '/laboratory': typeof LaboratoryRoute
  '/profile': typeof ProfileRoute
  '/profiles': typeof ProfilesRouteWithChildren
  '/profiles/manage': typeof ProfilesManageRoute
  '/profiles/': typeof ProfilesIndexRoute
  '/profiles/$profileId/challenges': typeof ProfilesProfileIdChallengesRoute
  '/profiles/$profileId/mentors': typeof ProfilesProfileIdMentorsRoute
  '/profiles/$profileId/portfolio': typeof ProfilesProfileIdPortfolioRoute
  '/profiles/$profileId/quest': typeof ProfilesProfileIdQuestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/feed': typeof FeedRoute
  '/laboratory': typeof LaboratoryRoute
  '/profile': typeof ProfileRoute
  '/profiles/manage': typeof ProfilesManageRoute
  '/profiles': typeof ProfilesIndexRoute
  '/profiles/$profileId/challenges': typeof ProfilesProfileIdChallengesRoute
  '/profiles/$profileId/mentors': typeof ProfilesProfileIdMentorsRoute
  '/profiles/$profileId/portfolio': typeof ProfilesProfileIdPortfolioRoute
  '/profiles/$profileId/quest': typeof ProfilesProfileIdQuestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/feed': typeof FeedRoute
  '/laboratory': typeof LaboratoryRoute
  '/profile': typeof ProfileRoute
  '/profiles': typeof ProfilesRouteWithChildren
  '/profiles/manage': typeof ProfilesManageRoute
  '/profiles/': typeof ProfilesIndexRoute
  '/profiles/$profileId/challenges': typeof ProfilesProfileIdChallengesRoute
  '/profiles/$profileId/mentors': typeof ProfilesProfileIdMentorsRoute
  '/profiles/$profileId/portfolio': typeof ProfilesProfileIdPortfolioRoute
  '/profiles/$profileId/quest': typeof ProfilesProfileIdQuestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/feed'
    | '/laboratory'
    | '/profile'
    | '/profiles'
    | '/profiles/manage'
    | '/profiles/'
    | '/profiles/$profileId/challenges'
    | '/profiles/$profileId/mentors'
    | '/profiles/$profileId/portfolio'
    | '/profiles/$profileId/quest'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/feed'
    | '/laboratory'
    | '/profile'
    | '/profiles/manage'
    | '/profiles'
    | '/profiles/$profileId/challenges'
    | '/profiles/$profileId/mentors'
    | '/profiles/$profileId/portfolio'
    | '/profiles/$profileId/quest'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/feed'
    | '/laboratory'
    | '/profile'
    | '/profiles'
    | '/profiles/manage'
    | '/profiles/'
    | '/profiles/$profileId/challenges'
    | '/profiles/$profileId/mentors'
    | '/profiles/$profileId/portfolio'
    | '/profiles/$profileId/quest'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  FeedRoute: typeof FeedRoute
  LaboratoryRoute: typeof LaboratoryRoute
  ProfileRoute: typeof ProfileRoute
  ProfilesRoute: typeof ProfilesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profiles': {
      id: '/profiles'
      path: '/profiles'
      fullPath: '/profiles'
      preLoaderRoute: typeof ProfilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laboratory': {
      id: '/laboratory'
      path: '/laboratory'
      fullPath: '/laboratory'
      preLoaderRoute: typeof LaboratoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profiles/': {
      id: '/profiles/'
      path: '/'
      fullPath: '/profiles/'
      preLoaderRoute: typeof ProfilesIndexRouteImport
      parentRoute: typeof ProfilesRoute
    }
    '/profiles/manage': {
      id: '/profiles/manage'
      path: '/manage'
      fullPath: '/profiles/manage'
      preLoaderRoute: typeof ProfilesManageRouteImport
      parentRoute: typeof ProfilesRoute
    }
    '/profiles/$profileId/quest': {
      id: '/profiles/$profileId/quest'
      path: '/$profileId/quest'
      fullPath: '/profiles/$profileId/quest'
      preLoaderRoute: typeof ProfilesProfileIdQuestRouteImport
      parentRoute: typeof ProfilesRoute
    }
    '/profiles/$profileId/portfolio': {
      id: '/profiles/$profileId/portfolio'
      path: '/$profileId/portfolio'
      fullPath: '/profiles/$profileId/portfolio'
      preLoaderRoute: typeof ProfilesProfileIdPortfolioRouteImport
      parentRoute: typeof ProfilesRoute
    }
    '/profiles/$profileId/mentors': {
      id: '/profiles/$profileId/mentors'
      path: '/$profileId/mentors'
      fullPath: '/profiles/$profileId/mentors'
      preLoaderRoute: typeof ProfilesProfileIdMentorsRouteImport
      parentRoute: typeof ProfilesRoute
    }
    '/profiles/$profileId/challenges': {
      id: '/profiles/$profileId/challenges'
      path: '/$profileId/challenges'
      fullPath: '/profiles/$profileId/challenges'
      preLoaderRoute: typeof ProfilesProfileIdChallengesRouteImport
      parentRoute: typeof ProfilesRoute
    }
  }
}

interface ProfilesRouteChildren {
  ProfilesManageRoute: typeof ProfilesManageRoute
  ProfilesIndexRoute: typeof ProfilesIndexRoute
  ProfilesProfileIdChallengesRoute: typeof ProfilesProfileIdChallengesRoute
  ProfilesProfileIdMentorsRoute: typeof ProfilesProfileIdMentorsRoute
  ProfilesProfileIdPortfolioRoute: typeof ProfilesProfileIdPortfolioRoute
  ProfilesProfileIdQuestRoute: typeof ProfilesProfileIdQuestRoute
}

const ProfilesRouteChildren: ProfilesRouteChildren = {
  ProfilesManageRoute: ProfilesManageRoute,
  ProfilesIndexRoute: ProfilesIndexRoute,
  ProfilesProfileIdChallengesRoute: ProfilesProfileIdChallengesRoute,
  ProfilesProfileIdMentorsRoute: ProfilesProfileIdMentorsRoute,
  ProfilesProfileIdPortfolioRoute: ProfilesProfileIdPortfolioRoute,
  ProfilesProfileIdQuestRoute: ProfilesProfileIdQuestRoute,
}

const ProfilesRouteWithChildren = ProfilesRoute._addFileChildren(
  ProfilesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  FeedRoute: FeedRoute,
  LaboratoryRoute: LaboratoryRoute,
  ProfileRoute: ProfileRoute,
  ProfilesRoute: ProfilesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
